const productos =
[
	{	
		"id": 1,
		"categoria": "Aywey",
		"nombre": "Aywey May",
		"precio": 738000,
		"unidades": 6,
		"alto": "161.5 mm",
		"ancho": "76.5 mm",
		"RAM": "8 GB",
		"almacenamiento": "256 GB",
		"imagenes": ["", ""]
	},
    {
		"id": 2,
		"categoria": "Aywey",
		"nombre": "Aywey Tempura",
		"precio": 500000,
		"unidades": 2,
		"alto": "157.6 mm",
		"ancho": "74.3 mm",
		"RAM": "12 GB",
		"almacenamiento": "256 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 3,
		"categoria": "Aywey",
		"nombre": "Aywey Noa",
		"precio": 98000,
		"unidades": 5,
		"alto": "164.6 mm",
		"ancho": "75.55 mm",
		"RAM": "8 GB",
		"almacenamiento": "128 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 4,
		"categoria": "UNIVERSE",
		"nombre": "UNIVERSE XYZ Flip Colors",
		"precio": 399900,"unidades": 1,
		"alto": "165.1 mm",
		"ancho": "71.9 mm",
		"RAM": "8 GB",
		"almacenamiento": "256 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 5,
		"categoria": "UNIVERSE",
		"nombre": "UNIVERSE XYZ Fall",
		"precio": 1069900,
		"unidades": 0,
		"alto": "154,9 mm",
		"ancho": "129,9 mm",
		"RAM": "12 GB",
		"almacenamiento": "256 GB",
			"imagenes": ["", ""]
    },
    {
		"id": 6,
		"categoria": "UNIVERSE",
		"nombre": "UNIVERSE_F24",
		"precio": 410000,
		"unidades": 5,
		"alto": "147 mm",
		"ancho": "70.6 mm",
		"RAM": "8 GB",
		"almacenamiento": "256 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 7,
		"categoria": "Shaomay",
		"nombre": "Shaomay Remid ",
		"precio": 99.900, 
		"unidades": 6,
		"alto": "168.60mm",
		"ancho": "8.17mm",
		"RAM": "4 GB",
		"almacenamiento": "128 GB",
		"imagenes": ["", ""]
    },
    {	"id": 8,
		"categoria": "Shaomay",
		"nombre": "Shaomay XLR8",
		"precio": 69.900,
		"unidades": 8,
		"alto": "168.4mm",
		"ancho": "76.3mm",
		"RAM": "4 GB",
		"almacenamiento": "128 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 9,
		"categoria": "Shaomay",
		"nombre": "Shaomay EnvyC",
		"precio": 105.900,
		"unidades": 4,
		"alto": "168.76mm",
		"ancho": "76.41mm",
		"RAM": "3 GB",
		"almacenamiento": "64 GB",
		"imagenes": ["", ""]
    },
    {
		"id": 10,
		"categoria": "Peraphone",
		"nombre": "Peraphone 13",
		"precio": 358.500,
		"unidades": 9,
		"alto": "146.7mm",
		"ancho": "71.5mm",
		"RAM": "4 GB",
		"almacenamiento": "128 GB",
		"imagenes": [" ", " "]
    },
    {
		"id": 11,
		"categoria": "Peraphone",
		"nombre": "Peraphone 14",
		"precio": 405.900,
		"unidades": 8,
		"alto": "146.7mm",
		"ancho": "71.5mm",
		"RAM": " 4 GB",
		"almacenamiento": "128 GB",
		"imagenes": [" ", " "]
    },
    {
		"id": 12,
		"categoria": "Peraphone",
		"nombre": "Peraphone 15",
		"precio": 501.900,
		"unidades": 10 ,
		"alto": "160.9mm",
		"ancho": "77.8mm",
		"RAM": "6 GB",
		"almacenamiento": "128 GB",
		"imagenes": [" ", " "]
    }
]